### ISSUE TITLE
cstl files are not extracted

### ISSUE THREAD

**Issue by pputnik** [Wolverator/CatSystem2-Simple-Translating-Tools#4]
unpack.py extracts texts from *.cst, and the extracted text is in the main(?) language of the game. 
Unfortunately, translation from *.cstl is not extracted :( 
Could you help, please?

**Comment by Wolverator** [comment]
Holy heck, i have 4 opened issues and GitHub didn't send me a single email about that XD
Huge apologies from me for not noticing this earlier T_T


Yes, by accident i've got request to use this tools for the game "Cyanotype Daydream -The Girl Who Dreamed the World-" and discovered that CatSystem2 has .cstl files for translations.

I see that The Math God is engineer of existing translating patches that utilise .cstl files, but i can't get in touch with them and have found no tool that i can automate to process .cstl files, my apologies in this regard.

But now i know about this and researching it. Hope i can achieve some solution in the next week or two 😅

**Comment by Wolverator** [comment]
Found a tool for cstl files, WIP for automating that tool via my code.
