### ISSUE TITLE
Translated xlsx files not getting converted but imported + update order?

### ISSUE THREAD

**Issue by anphex** [Wolverator/CatSystem2-Simple-Translating-Tools#8]
Hi!

First of all, thank you for this nice tool! I am running into the issue that when making a test unpack/pack run I translated the very first line of Grisaia to see if it works but the untranslated line persists. This confuses me as the line shoul change, right? The pack went fine and I used the highest number for the update file there is.
When I edit the files in "source game files/texts" directly it works.

Also there is the steam +18 restoration patch from HBC which also seems to contain scripts. Would there be a way to merge my translation and this restoration patch? Best case would be if I could just extract the scripts right from this restoration patch and reimport it into this restoration patch as one package.

**Comment by Wolverator** [comment]
Hi! Glad my tools were of help ^_^

Let me guess, you did not translate scene_titles and translated only one single first line of actual text? :D 
That was not a scenario i had during tests of my tools, so i've missed this tricky case.
Anyway, it's fixed now. (hope that won't bring new bugs XD)

Regarding +18 restoration patch: i've done one and uploaded to F95Zone forum (not sure how GitHub handles links to pirate adult web-sites. so you better use Google or write me directly at Discord `sherekhanromeo` if you need any help with that).

That single-file-patch has "restored" and combined content of both steam and +18 game versions. I suggest you get that patch and translate it's contents. That's exactly what i'm doing for my language 😅
