### ISSUE TITLE
"in <string>" requires string as left operand, not float (code fixes)

### ISSUE THREAD

**Issue by anphex** [Wolverator/CatSystem2-Simple-Translating-Tools#9]
Hi! Me again :)

Thank you for this turbo fast response on my prior issue and explaining the mistakes.
Though now I get the issue mentioned in the topic title when repacking. I have a video attached for better view on how I did it. I was basically just a unpack-pack test run to see if it works smoothly out of the box.

https://anphex.one/index.php/s/jmYwsbcnfT4s2WD

Another question: In the extracted original text there are those brackets around every word. Is this important formatting you have to keep or can you write text as you would normally into the fields for translated text?

Some recommendations for the code:
- either implement short type checks OR force convert everything to strings so int/float errors are a thing of the past
- expand the readme.md since currently a few things are unclear: where do I put the final files after translation? Do I just keep them in their folder or do I have to move them to  "clean localization texts"? What is the easiest way to verify the pipeline and start translating confidently? What is the behaviour with unsupported characters? Will those be skipped or will there be an unhandled exception in the engine?

Thank you very much for your time.

**Comment by Wolverator** [comment]
Would you mind attaching your copy of `com14.xlsx` to let me check what on Earth there could be triggering that error? 😅 

Will do exact fix right away, will optimize whole code and write a clearer ReadMe(at least i hope it will be so XD) a bit later, many thanks!

Regarding square brackets: Translations you write in Excel will have those brackets inserted via my code, so it's fine to write translations without it. They are left there in original text to let my tools find exact symbols sequence when replacing original lines with new ones. Tho, other special symbols like `\n` are not replaced and should be transferred into translated text manually.

**Comment by Wolverator** [comment]
Also i do have code that replaces symbols CS2 game engine does not supports with ones it does, but i doubt i have full list of those need to be replaced, so there might be some 😓

**Comment by anphex** [comment]
Of course!

Here is the file, note that it's rawly extracted and not even opened once:
[com14.xlsx](https://github.com/Wolverator/CatSystem2-Simple-Translating-Tools/files/14233639/com14.xlsx)

And for the type errors: I know you're fixing those unsupported letters already but what I meant were type errors like when the tools requires strings but gets a float or int. I am already surprised you are working with xlsx files, in my memory those have a habit of "auto formatting" cells which turns cells with numbers into a float (what makes sense from the viewpoint of spreadshets). So I would implement a codeline than goes basicaly 

`if type == float or type == int)`
	type = str(type)

And thank you for your enthusiasm. I am super glad to see some developer being this active in this niche :D
